name: Terraform GPO Deployment with Report

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform Changes
        run: terraform apply -auto-approve

      - name: Generate GPO Report using GPOZaurr
        run: |
          Import-Module GPOZaurr
          Show-GPOZaurr | Out-File GPOAuditReport.html -Encoding utf8

      - name: Push Report to GitHub
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote set-url origin https://x-access-token:${{ secrets.Token }}@github.com/KarthikaVG/terraform-gpo.git
          git add GPOAuditReport.html
          git commit -m "Add updated GPO audit report"
          git push