name: Terraform GPO Deployment with Report

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform Changes
        run: terraform apply -auto-approve

      - name: Install GPOZaurr
        shell: powershell
        run: Install-Module -Name GPOZaurr -Force -Scope CurrentUser

      - name: Generate CIS GPO Report
        shell: powershell
        run: |
          Import-Module GPOZaurr
          Get-GPOZaurrReport -Path GPOAuditReport.html

      - name: Push Report to GitHub
        shell: powershell
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add GPOAuditReport.html
          git commit -m "Add GPO audit report"
          git push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
