name: Terraform GPO Deployment with Report

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform Changes
        run: terraform apply -auto-approve

      - name: Install GPOZaurr
        shell: pwsh
        run: |
          Install-Module -Name GPOZaurr -Force -Scope CurrentUser

      - name: Generate GPO Audit Report
        shell: pwsh
        run: |
          Import-Module GPOZaurr
          Invoke-GPOZaurr -Path "$PWD\GPOAuditReport.html"

      - name: Push Report to GitHub
        shell: pwsh
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/KarthikaVG/terraform-gpo.git
          git add GPOAuditReport.html
          git commit -m "Add GPO audit report"
          git push
